# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: build rpm el8
        env:
          SPEC_FILE: haproxy.spec
          RELEASE_TAG: v2.4.17
          RELEASE_GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}
        uses: docker://yoannguion/rpmbuilder:el8-release-to-github

      - uses: actions/checkout@v2
      - name: build rpm el9
        env:
          SPEC_FILE: haproxy.spec
          RELEASE_TAG: v2.4.17
          RELEASE_GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}
        uses: docker://yoannguion/rpmbuilder:el9-release-to-github
